### ISSUE TITLE
image in basic example is truncated in way that creates a lot of whitespace in README

### ISSUE THREAD

**Issue by MatthewCaseres** [cbalona/reinsurance#1]
This issue is a bit strange because when I view the markdown preview in github.dev it renders fine. So I guess the issue is not with the syntax but with GitHub's images?

**Comment by cbalona** [comment]
Hi @MatthewCaseres. I am not sure I understand the problem. Could you post a picture explaining what you mean?

**Comment by MatthewCaseres** [comment]
When I view  https://github.com/cbalona/reinsurance I see this:
![Screenshot 2023-05-30 at 6 15 35 PM](https://github.com/cbalona/reinsurance/assets/43053796/41882ff5-e56c-4054-a120-770bc53e2558)
It doesn't display the full figure and creates some white space.

But when viewed from here - https://github.dev/cbalona/reinsurance I am having no issues.

**Comment by cbalona** [comment]
That is quite strange. Can you try to refresh your cache in your browser and see if it fixes it? Should be `Ctrl + Shift + R`.

**Comment by MatthewCaseres** [comment]
Indeed strange since I guess you are not seeing this. I did refresh the cache and it happens on both chrome and safari.

**Comment by cbalona** [comment]
@MatthewCaseres I have re-uploaded the image. Let me know if that fixes it.

**Comment by MatthewCaseres** [comment]
Now it is totally not rendering, there is just the placeholder to indicate that the image is broken. Checked on multiple computers. Usually the image would be included in the repo and the link would be directly to it, but it seems like you want to resize the image so you don't want to do the markdown link syntax.

I tried downloading the image previously and resizing it in an image editor but the quality degraded a bit. The dask docs indicate we can export this graph as an svg, and then you will be able to resize it more freely https://docs.dask.org/en/stable/graphviz.html in an editor without degradation, and can link to it with a relative path using markdown syntax

<img width="565" alt="Screenshot 2023-06-10 at 2 08 00 PM" src="https://github.com/cbalona/reinsurance/assets/43053796/427700c2-0df3-4259-8c3e-1974f7a15d66">

**Comment by cbalona** [comment]
Should be fixed now, I used the wrong link.

> Usually the image would be included in the repo and the link would be directly to it, but it seems like you want to resize the image so you don't want to do the markdown link syntax.

For now I am just linking an externally hosted image until I develop examples that I can link to within the repo.

**Comment by MatthewCaseres** [comment]
image now visible in full

<img width="498" alt="Screenshot 2023-06-10 at 2 40 57 PM" src="https://github.com/cbalona/reinsurance/assets/43053796/f12bf740-2084-4cf6-af52-7bacb712b3d9">
